# Note: cost/units are WIP
coins:
  - ticker: "bitcoin"
    cost: 1000
    units: 5
  - ticker: "ethereum"
    cost: 100
    units: 1
  - ticker: "bitcoin-cash"
    cost: 100
    units: 1
misc:
  currency: "USD"

# Valid Currencies:
# "AUD", "BRL", "CAD", "CHF", "CLP", "CNY", "CZK", "DKK", "EUR", "GBP", "HKD", "HUF",
# "IDR", "ILS", "INR", "JPY", "KRW", "MXN", "MYR", "NOK", "NZD", "PHP", "PKR", "PLN",
# "RUB", "SEK", "SGD", "THB", "TRY", "TWD", "ZAR"
