# Valid coin tickers:
# https://coinmarketcap.com/coins/
# Mouse over the links to find the ticker
# E.g. https://coinmarketcap.com/currencies/bitcoin/

coins:
  - ticker: "bitcoin"
    cost: 1000
    units: 5
  - ticker: "ethereum"
    cost: 100
    units: 1
  - ticker: "bitcoin-cash"
    cost: 100
    units: 1
  - ticker: "dash"
    cost: 100
    units: 1
  - ticker: "ripple"
    cost: 100
    units: 1
  - ticker: "monero"
    cost: 100
    units: 1
  - ticker: "neo"
    cost: 100
    units: 1
  - ticker: "iota"
    cost: 100
    units: 1
  - ticker: "nem"
    cost: 100
    units: 1
  - ticker: "qtum"
    cost: 100
    units: 1
  - ticker: "ethereum-classic"
    cost: 100
    units: 1
misc:
  currency: "USD"

# Valid Currencies:
# "AUD", "BRL", "CAD", "CHF", "CLP", "CNY", "CZK", "DKK", "EUR", "GBP", "HKD", "HUF",
# "IDR", "ILS", "INR", "JPY", "KRW", "MXN", "MYR", "NOK", "NZD", "PHP", "PKR", "PLN",
# "RUB", "SEK", "SGD", "THB", "TRY", "TWD", "ZAR"
